cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #http://localhost:8000/cart
    path('', views.index, name="cart-index"),
    #http://localhost:8000/cart/confirm-card
    path('contact-info/', views.contactInfo, name="contact-info"),
    path('confirm-card/', views.pay, name="confirm-card"),
    #http://localhost:8000/cart/review
    path('review/', views.review, name="review"),
    #http://localhost:8000/cart/receipt
    path('receipt/', views.receipt, name="receipt"),

    path('addToCart/', views.addToCart, name="addToCart"),
    path('removeFromCart/', views.removeFromCart, name="removeFromCart")
]

ship_o_cereal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('user/', include('user.urls'))
]

handler400 = 'error.views.error_400_view'

handler403 = 'error.views.error_403_view'

handler404 = 'error.views.error_404_view'

handler500 = 'error.views.error_500_view'

cart/models.py
from django.db import models
from products.models import Product
from user.models import Order

# Create your models here.

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.IntegerField()

products/models.py
from django.db import models

# Create your models here.

class ProductManufacturer(models.Model):
    name = models.CharField(max_length = 255)

    def __str__(self):
        return self.name

class ProductTag(models.Model):
    name = models.CharField(max_length = 255)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length = 255)
    manufacturer = models.ForeignKey(ProductManufacturer, on_delete = models.CASCADE)
    price = models.IntegerField()
    description = models.CharField(max_length = 255, blank = True)
    nutriInfo = models.CharField(max_length = 255, blank = True)
    amount = models.IntegerField()
    tag = models.ForeignKey(ProductTag, on_delete = models.CASCADE)

class ProductImage(models.Model):
    image = models.CharField(max_length = 9999)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)

cart/forms/NewCardForm.py
from django.forms import widgets, ModelForm
from user.models import PaymentInfo

class NewCardForm(ModelForm):
    class Meta:
        model = PaymentInfo
        exclude = ['id', 'profile']
        widgets = {
            'cardHolder': widgets.TextInput(attrs={'class': 'form-control'}),
            'cardNumber': widgets.TextInput(attrs={'class': 'form-control'}),
            'expDate': widgets.TextInput(attrs={'class': 'form-control'}),
            'cvc': widgets.TextInput(attrs={'class': 'form-control'})
        }

cart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from cart.forms.NewCardForm import NewCardForm
from user.forms.profile_form import ProfileForm
from user.models import PaymentInfo, Address
from error.views import *

from user.models import Profile, Order
from cart.models import OrderItem, Product

# Create your views here.

def order_item_queries_to_list(queries):
    items = []
    for item in queries:
        i = {
            "product": {
                "name": item.product.name,
                "price": item.product.price
            },
            "quantity": item.quantity,
            "order_id": item.order.id
        }
        items.append(i)
    return items

def construct_user_dict(request):
    user_info = {
        'name': request.user.profile.name,
        'email': request.user.profile.email,
        'phone': request.user.profile.phone,
        'streetName': request.user.profile.address.streetName,
        'houseNumber': request.user.profile.address.houseNumber,
        'city': request.user.profile.address.city,
        'country': request.user.profile.address.country,
        'postalCode': request.user.profile.address.postNumber
    }
    return user_info

def getTotalPrice(orderItems):
    total = 0
    for item in orderItems:
        total += item.quantity * item.product.price
    return total

@login_required
def index(request):
    profile = Profile.objects.filter(user=request.user).first()
    if profile is None:
        return redirect('profile')
    else:
        order = Order.objects.filter(profile=profile, status='In Progress').first()
        request.session['totalPrice'] = getTotalPrice(OrderItem.objects.filter(order=order))
        return render(request, 'cart/index.html', {
            'profile': profile,
            'address': profile.address,
            'items': OrderItem.objects.filter(order=order),
            'totalPrice': request.session['totalPrice']
        })

def addToCart(request):
    if request.user.is_authenticated:
        profile = Profile.objects.filter(user=request.user).first()
        if profile is None:
            return JsonResponse({'amount': -1})
        order = Order.objects.filter(profile=profile, status='In Progress').first()
        if order is None:
            order = Order()
            order.profile = profile
            order.status = 'In Progress'
        product = Product.objects.filter(id=request.POST['id']).first()
        item = OrderItem.objects.filter(order=order, product=product).first()
        if item is None:
            item = OrderItem()
            item.product = product
            item.quantity = int(request.POST['amount'])
            item.order = order
        else:
            item.quantity += int(request.POST['amount'])
        order.save()
        item.save()
        return JsonResponse({'amount': item.quantity, 'id': request.POST['id']})
    return HttpResponseForbidden()


def removeFromCart(request):
    if request.user.is_authenticated:
        profile = Profile.objects.filter(user=request.user).first()
        order = Order.objects.filter(profile=profile, status='In Progress').first()
        product = Product.objects.filter(id=request.POST['id']).first()
        item = OrderItem.objects.filter(order=order, product=product).first()
        item.delete()
        request.session['totalPrice'] = getTotalPrice(OrderItem.objects.filter(order=order))
        return JsonResponse({'id': request.POST['id'], 'totalPrice': request.session['totalPrice']})

def cartEmptyCheck(request):
    order = Order.objects.filter(profile=request.user.profile, status='In Progress').first()
    if order is None:
        return error_400_view(request, None)
    product = OrderItem.objects.filter(order=order).first()
    if product is None:
        return error_400_view(request, None)

@login_required
def contactInfo(request):
    isEmpty = cartEmptyCheck(request)

    if isEmpty is not None:
        return isEmpty

    profile = Profile.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = ProfileForm(instance=profile, data=request.POST)
        if form.is_valid():
            if profile.address is None:
                address_instance = Address()
            else:
                address_instance = request.user.profile.address
            address_instance.country = request.POST['country']
            address_instance.city = request.POST['city']
            address_instance.houseNumber = request.POST['houseNumber']
            address_instance.streetName = request.POST['streetName']
            address_instance.postNumber = request.POST['postNumber']
            address_instance.save()
            profile = form.save(commit=False)
            profile.user = request.user
            profile.address = address_instance
            profile.save()
            return redirect('confirm-card')
    if request.user.profile.address is None:
        initial = {}
    else:
        initial = {
            'country': request.user.profile.address.country,
            'city': request.user.profile.address.city,
            'houseNumber': request.user.profile.address.houseNumber,
            'streetName': request.user.profile.address.streetName,
            'postNumber': request.user.profile.address.postNumber
        }
    return render(request, 'cart/contact_info.html', {
        'form': ProfileForm(instance=profile, initial=initial),
    })

@login_required
def pay(request):
    isEmpty = cartEmptyCheck(request)

    if isEmpty is not None:
        return isEmpty

    if request.method == 'POST':
        form = NewCardForm(data=request.POST)
        if form.is_valid():
            newCard = form.save(commit=False)
            request.session['currentCard'] = {
                'cardNumber': newCard.cardNumber,
                'cardHolder': newCard.cardHolder,
                'expDate': newCard.expDate,
                'cvc': newCard.cvc,
            }
            return redirect('review')
    else:
        if 'currentCard' in request.session.keys():
            form = NewCardForm(initial=request.session['currentCard'])
        else:
            form = NewCardForm()

    return render(request, 'cart/pay.html', {
        'cardForm': form,
    })

@login_required
def review(request):
    isEmpty = cartEmptyCheck(request)

    if isEmpty is not None:
        return isEmpty

    if 'currentCard' in request.session.keys():
        profile = Profile.objects.filter(user=request.user).first()
        order = Order.objects.filter(profile=profile, status='In Progress').first()

        return render(request, 'cart/review.html', {
            'profile': profile,
            'address': profile.address,
            'items': OrderItem.objects.filter(order=order),
            'cardNumber': request.session['currentCard']['cardNumber'],
            'totalPrice': request.session['totalPrice']
        })
    return error_400_view(request, None)

@login_required
def receipt(request):
    isEmpty = cartEmptyCheck(request)

    if isEmpty is not None:
        return isEmpty

    if 'currentCard' in request.session.keys():
        user_info = construct_user_dict(request)
        order = Order.objects.filter(profile=request.user.profile, status='In Progress').first()
        order.status = 'Done'
        order.save()
        order_list = order_item_queries_to_list(OrderItem.objects.filter(order=order))
        return render(request, 'cart/receipt.html', {"user_info": user_info, "address": request.user.profile.address, "items": order_list, "basic_user_info": {'name': user_info['name']}, "totalPrice": request.session['totalPrice']})

    return error_400_view(request, None)

templates/cart/contact_info.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/contact_info.css' %}">
<div id="allItems">
    <h3>Contact Information:</h3>
    <form class="form form-horizontal" id="form" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    <form action = "{% url 'cart-index' %}" class = "button-form">
        <button type = "submit">Go Back</button>
    </form>
</div>
{% endblock %}

templates/cart/index.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    <div id = "cereal-container">
        {% csrf_token %}
        <script>
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            const removeIndex = "{% url 'removeFromCart' %}";
        </script>
        {% for item in items %}
        <div class = "cereal-cart-info-box" id = "{{ item.product.id }}container">
            <button class = "del-button" value="{{ item.product.id }}">X</button>
            <img src="{{ item.product.productimage_set.first.image }}"/>
            <h3>{{ item.product.name }}</h3>
            <div class = "cereal-info">
                <p>Amount: {{ item.quantity }}</p>
                <p>Price: {{ item.quantity|mul:item.product.price }} kr.</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div id = "right-side-container">
        <h2 id = "total-header">Total: {{ totalPrice }}kr.</h2>
        <div id = "user-info-container">
            <p>Name: {{ profile.name }}</p>
            <p>Phone number: {{ profile.phone }}</p>
            {% if address is not None %}
                <p>Address: {{ address.streetName }}  {{ address.houseNumber }} {{ address.postalCode }} {{ address.city }} {{ address.country }}</p>
            {% endif %}
        </div>
        <div id = "button-container">
            <form action="{% url 'contact-info' %}" class = "button-form">
                <button type = "submit">Continue</button>
            </form>
            <form action = "{% url 'catalog-page' %}" class = "button-form">
                <button type = "submit">Go Back</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/cart/pay.html
{% extends 'base.html' %}
{% load static %}
<head>
    <title>Catalog</title>
</head>
{% block content %}
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <h3>New Card:</h3>
    <div id = "register-card">
        <form method="post">

            {% csrf_token %}
            {{ cardForm }}
            <input type="submit" value="Submit">
        </form>
    </div>

    <form action = "{% url 'contact-info' %}" class = "button-form">
        <button type = "submit">Go Back</button>
    </form>

{% endblock %}

templates/cart/receipt.html
{% extends 'base.html' %}
{% load static %}
<head>
    <title>Catalog Review</title>
</head>
{% block content %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <div id = "receipt-container">
        <h1>Receipt</h1>
        <h3>Thank you for your purchase.</h3>
        <h3>Your purchase will be delivered to {{ address.streetName }}  {{ address.houseNumber }} on May 25th.</h3>
        <button id = "receipt-button">Print Receipt</button>
        <br>
        <form action = "{% url 'catalog-page' %}" class = "button-form">
            <button type = "submit">Return to Catalog</button>
        </form>
    </div>
    <!-- The following script tags are needed to be able to access the django variables in the JS file -->
    <script>
        let totalAmount = {{ totalPrice }};
    </script>
    <!--https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#json-script-->
    {{ items|json_script:"cart-items" }}
    {{ basic_user_info|json_script:"user-info" }}
    <script type="text/javascript" src="{% static 'js/receipt.js' %}"></script>
{% endblock %}

templates/cart/review.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
<head>
    <title>Catalog Review</title>
</head>
{% block content %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <h1>Review</h1>
    <div id = "cereal-container">
        {% for item in items %}
        <div class = "cereal-cart-info-box" id = "{{ item.product.id }}container">
            <img src="{{ item.product.productimage_set.first.image }}"/>
            <h3>{{ item.product.name }}</h3>
            <div class = "cereal-info">
                <p>Amount: {{ item.quantity }}</p>
                <p>Price: {{ item.quantity|mul:item.product.price }} kr.</p>
                <script>
                    prices[{{ item.product.id }}] = {{ item.quantity|mul:item.product.price }};
                </script>
            </div>
        </div>
        {% endfor %}
    </div>
    <div id = "right-side-container">
        <h2 id = "total-header">Total: {{ totalPrice }}kr.</h2>
        <div id = "user-info-container">
            <p>Name: {{ profile.name }}</p>
            <p>Phone number: {{ profile.phone }}</p>
            <p>Address: {{ address.streetName }}  {{ address.houseNumber }} {{ address.postalCode }} {{ address.city }} {{ address.country }}</p>
            <p>Card: Ending with {{ cardNumber | slice:"-4:" }}</p>
        </div>
        <div id = "button-container">
            <form action="{% url 'receipt' %}" class = "button-form">
                <button type = "submit">Finalize Payment</button>
            </form>
            <form action = "{% url 'confirm-card' %}" class = "button-form">
                <button type = "submit">Go Back</button>
            </form>
        </div>
    </div>
{% endblock %}